name: Linux

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup V
        run: |
          curl -Lo v_linux.zip https://github.com/vlang/v/releases/latest/download/v_linux.zip
          unzip -o v_linux.zip
          mv v ~/v
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [tcc, gcc, clang]
        optimization: ['', '-W -cstrict']
        exclude:
          - cc: tcc
            optimization: '-W -cstrict'
      fail-fast: false
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }} ${{ matrix.optimization }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v -showcc self && v doctor
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Build
        run: v -o vzit .
      - name: Test
        run: |
          ./vzit --version
          v test .

  test-sanitzed:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cc: gcc
            sanitizer: address,leak,undefined,shift,shift-exponent,shift-base,integer-divide-by-zero,unreachable,vla-bound,null,return,signed-integer-overflow,bounds,bounds-strict,alignment,object-size,float-divide-by-zero,float-cast-overflow,nonnull-attribute,returns-nonnull-attribute,bool,enum,vptr
          - cc: gcc
            sanitizer: thread
          - cc: clang
            sanitizer: address,leak,undefined
          - cc: clang
            sanitizer: thread
          - cc: clang
            sanitizer: memory
      fail-fast: false
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v -showcc self && v doctor
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Build
        run: v -cflags -fsanitize=${{ matrix.sanitizer }} -o vzit .
      - name: Test
        run: |
          ./vzit --version
          v test .
